# Generated by Django 5.1.4 on 2025-01-19 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=20, verbose_name='Preferred Contact Method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='NAME')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.IntegerField(default=0, verbose_name='Passengers')),
                ('child_count', models.IntegerField(default=0, verbose_name='Kids')),
                ('total_quantity', models.IntegerField(default=0, editable=False, verbose_name='Total Travelers')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Cost (CZK)')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Customer Address')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='card', max_length=20, verbose_name='Payment Method')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status')),
                ('travel_preferences', models.TextField(blank=True, null=True, verbose_name='Travel Preferences')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tour Purchase',
                'verbose_name_plural': 'Tour Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='viewer.city')),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('international_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='International Code')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='viewer.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='viewer.country'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('Stars', models.IntegerField(blank=True, default=3, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Hotel Image')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='viewer.city', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Hotels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('tour_purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='viewer.tourpurchase', verbose_name='Tour Purchase')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(default='Tour name ', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Departure date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return date')),
                ('stay_duration', models.IntegerField(blank=True, null=True, verbose_name='Duration of stay (days)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_images/', verbose_name='Trip Image')),
                ('meal_type', models.CharField(choices=[('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], max_length=2, verbose_name='Meal type')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Is promoted')),
                ('adult_seats', models.IntegerField(verbose_name='Number of seats')),
                ('child_seats', models.IntegerField(verbose_name='Number of seats for Kids')),
                ('price_per_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per passenger (czk)')),
                ('price_per_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Kid (czk)')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='viewer.hotel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_travel_info', to='viewer.city')),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures_airport', to='viewer.airport', verbose_name='Departure (airport)')),
                ('departure_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='viewer.city', verbose_name='Departure (city)')),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals_airport', to='viewer.airport', verbose_name='Destination (airport)')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='viewer.city', verbose_name='Destination (city)')),
            ],
            options={
                'verbose_name': 'Travel Information',
                'verbose_name_plural': 'Travel Information',
                'ordering': ['tour_name'],
            },
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='viewer.travelinfo', verbose_name='Trip'),
        ),
    ]
