# Generated by Django 5.1.4 on 2025-01-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_hotels', to='viewer.city', verbose_name='City'),
        ),
    ]
