# Generated by Django 5.1.4 on 2024-12-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_continent_name_country_city_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='viewer.city')),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'ordering': ['name'],
            },
        ),
    ]
