# Generated by Django 5.1.4 on 2025-01-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_infos', to='viewer.employee', verbose_name='Assigned Employee'),
        ),
    ]
