# Generated by Django 5.1.4 on 2024-12-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=32, unique=True)),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Departure date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return date')),
                ('stay_duration', models.IntegerField(blank=True, null=True, verbose_name='Duration of stay (days)')),
                ('meal_type', models.CharField(choices=[('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], max_length=2, verbose_name='Meal type')),
                ('price_per_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per adult (CZK)')),
                ('price_per_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per child (CZK)')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Is promoted')),
                ('adult_seats', models.IntegerField(verbose_name='Number of seats for adults')),
                ('child_seats', models.IntegerField(verbose_name='Number of seats for children')),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures_airport', to='viewer.airport', verbose_name='Departure (airport)')),
                ('departure_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='viewer.city', verbose_name='Departure (city)')),
                ('destination_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals_airport', to='viewer.airport', verbose_name='Destination (airport)')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='viewer.city', verbose_name='Destination (city)')),
                ('destination_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals_hotel', to='viewer.hotel', verbose_name='Destination (hotel)')),
            ],
            options={
                'verbose_name': 'Travel Information',
                'verbose_name_plural': 'Travel Information',
                'ordering': ['tour_name'],
            },
        ),
    ]
