# Generated by Django 5.1.4 on 2024-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_travelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
