# Generated by Django 5.1.4 on 2025-01-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_travelinfo_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to='viewer.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_process', 'In Process'), ('closed', 'Closed'), ('not_assigned', 'Not Assigned')], default='not_assigned', max_length=20, verbose_name='Status'),
        ),
    ]
