# Generated by Django 5.1.4 on 2024-12-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_continent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinfo',
            name='tour_name',
            field=models.CharField(default='Default Tour Name', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='TourPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.IntegerField(default=0, verbose_name='Počet dospělých')),
                ('child_count', models.IntegerField(default=0, verbose_name='Počet dětí')),
                ('total_quantity', models.IntegerField(default=0, editable=False, verbose_name='Celkové množství')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='viewer.travelinfo', verbose_name='Zájezd')),
            ],
            options={
                'verbose_name': 'Nákup zájezdu',
                'verbose_name_plural': 'Nákupy zájezdů',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('age', models.IntegerField(verbose_name='Věk')),
                ('type', models.CharField(choices=[('adult', 'Dospělý'), ('child', 'Dítě')], max_length=5, verbose_name='Typ cestujícího')),
                ('tour_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='viewer.tourpurchase', verbose_name='Nákup zájezdu')),
            ],
            options={
                'verbose_name': 'Cestující',
                'verbose_name_plural': 'Cestující',
                'ordering': ['name'],
            },
        ),
    ]
