# Generated by Django 5.1.4 on 2025-01-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_contactmessage_assigned_to_contactmessage_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.employee', verbose_name='Author')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comments', to='viewer.contactmessage', verbose_name='Related Contact Message')),
            ],
            options={
                'verbose_name': 'Contact Message Comment',
                'verbose_name_plural': 'Contact Message Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
