# Generated by Django 5.1.4 on 2024-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_travelinfo_tour_name_tourpurchase_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Celková cena (CZK)'),
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
