# Generated by Django 5.1.4 on 2025-01-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_contactmessagecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinfo',
            name='Hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='viewer.hotel'),
        ),
    ]
