# Generated by Django 5.1.4 on 2024-12-07 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_tourpurchase_total_price_delete_traveler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpurchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour Purchase', 'verbose_name_plural': 'Tour Purchases'},
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update date '),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='adult_count',
            field=models.IntegerField(default=0, verbose_name='Number of Adult'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='child_count',
            field=models.IntegerField(default=0, verbose_name='Number od kids'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Price (CZK)'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='total_quantity',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total quantity'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='viewer.travelinfo', verbose_name='Trip'),
        ),
    ]
