# Generated by Django 5.1.4 on 2024-12-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_tourpurchase_options_tourpurchase_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='international_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
