# Generated by Django 5.1.4 on 2024-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_country_international_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='international_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='International Code'),
        ),
    ]
