# Generated by Django 5.1.4 on 2024-12-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_country_international_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='cities_set', to='viewer.hotel'),
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='destination_hotels',
            field=models.ManyToManyField(blank=True, related_name='travel_infos', to='viewer.hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_hotels', to='viewer.city'),
        ),
    ]
