# Generated by Django 5.1.4 on 2024-12-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_city_hotels_travelinfo_destination_hotels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
