# Generated by Django 5.1.4 on 2024-12-07 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_travelinfo_created_at_travelinfo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpurchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At '),
        ),
    ]
