# Generated by Django 5.1.4 on 2024-12-07 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_tourpurchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpurchase',
            name='adult_count',
            field=models.IntegerField(default=0, verbose_name='passengers'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='child_count',
            field=models.IntegerField(default=0, verbose_name='KIDS'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Cost (czk)'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='total_quantity',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total Travelers'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at '),
        ),
    ]
