# Generated by Django 5.1.4 on 2024-12-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_travelinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='tour_mame',
            field=models.ManyToManyField(blank=True, related_name='tour_purchases', to='viewer.travelinfo'),
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='adult_seats',
            field=models.IntegerField(verbose_name='Number of seats'),
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='child_seats',
            field=models.IntegerField(verbose_name='Number of seats for Kids'),
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='price_per_adult',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per passenger (czk)'),
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='price_per_child',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Kid (czk)'),
        ),
    ]
