# Generated by Django 5.1.4 on 2024-12-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_tourpurchase_tour_mame_alter_travelinfo_adult_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpurchase',
            name='tour_mame',
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='tour_mame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_purchases', to='viewer.travelinfo'),
        ),
    ]
