# Generated by Django 5.1.4 on 2024-12-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_remove_tourpurchase_tour_mame_tourpurchase_tour_mame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpurchase',
            name='tour_mame',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_purchases', to='viewer.travelinfo', verbose_name='Trip - name'),
        ),
    ]
