# Generated by Django 5.1.4 on 2024-12-08 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_alter_tourpurchase_tour_mame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpurchase',
            name='tour_mame',
        ),
        migrations.AddField(
            model_name='continent',
            name='continent_code',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='adult_count',
            field=models.IntegerField(default=0, verbose_name='Passengers'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='child_count',
            field=models.IntegerField(default=0, verbose_name='Kids'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
