# Generated by Django 5.1.4 on 2024-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_remove_tourpurchase_tour_mame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent_code',
            field=models.CharField(editable=False, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='NAME'),
        ),
    ]
