# Generated by Django 5.1.4 on 2024-12-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_alter_continent_continent_code_alter_continent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentCountryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=32, unique=True)),
                ('country_name', models.CharField(max_length=50)),
                ('international_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city_name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Country',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='continent_code',
        ),
    ]
