# Generated by Django 5.1.4 on 2024-12-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_continentcountrycity_rename_country_city_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_hotels', to='viewer.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Stars',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
