# Generated by Django 5.1.4 on 2024-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_remove_travelinfo_destination_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
    ]
