# Generated by Django 5.1.4 on 2024-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContinentCountryCity',
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Phone'),
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Special Requests'),
        ),
    ]
