# Generated by Django 5.1.4 on 2024-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_delete_continentcountrycity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=20, verbose_name='Preferred Contact Method'),
        ),
    ]
