# Generated by Django 5.1.4 on 2024-12-11 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_contactmessage_address_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpurchase',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='card', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='tourpurchase',
            name='travel_preferences',
            field=models.TextField(blank=True, null=True, verbose_name='Travel Preferences'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='tourpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Cost (CZK)'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('tour_purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='viewer.tourpurchase', verbose_name='Tour Purchase')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
