# Generated by Django 5.1.4 on 2024-12-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0031_tourpurchase_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/', verbose_name='Trip Image'),
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='tour_name',
            field=models.CharField(default='Tour name ', max_length=200, unique=True),
        ),
    ]
