# Generated by Django 5.1.4 on 2024-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0032_travelinfo_image_alter_travelinfo_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Hotel Image'),
        ),
    ]
